import type { Category } from "@/types/content";

export const categories: Category[] = [
  {
    id: "V1",
    slug: "v5-encoding-sanitization",
    title: "Encoding and Sanitization",
    description: "Context-aware output encoding, sanitization, and safe handling of untrusted content.",
    icon: "Braces",
    color: "teal",
    standardVersion: "5.0.0",
  },
  {
    id: "V2",
    slug: "v5-validation-business-logic",
    title: "Validation and Business Logic",
    description: "Input validation, business rule enforcement, workflow integrity, and anti-abuse controls.",
    icon: "ListChecks",
    color: "cyan",
    standardVersion: "5.0.0",
  },
  {
    id: "V3",
    slug: "v5-web-frontend-security",
    title: "Web Frontend Security",
    description: "Browser-facing security controls for client-side code, content, and web platform features.",
    icon: "PanelsTopLeft",
    color: "blue",
    standardVersion: "5.0.0",
  },
  {
    id: "V4",
    slug: "v5-api-web-service",
    title: "API and Web Service",
    description: "Security requirements for APIs, web services, endpoints, and service-to-service interfaces.",
    icon: "Webhook",
    color: "indigo",
    standardVersion: "5.0.0",
  },
  {
    id: "V5",
    slug: "v5-file-handling",
    title: "File Handling",
    description: "Secure upload, storage, processing, download, and deletion of files and related metadata.",
    icon: "Files",
    color: "violet",
    standardVersion: "5.0.0",
  },
  {
    id: "V6",
    slug: "v5-authentication",
    title: "Authentication",
    description: "Identity proofing, credential handling, authentication factors, and account lifecycle controls.",
    icon: "Fingerprint",
    color: "fuchsia",
    standardVersion: "5.0.0",
  },
  {
    id: "V7",
    slug: "v5-session-management",
    title: "Session Management",
    description: "Session token generation, binding, renewal, expiration, storage, and invalidation.",
    icon: "KeyRound",
    color: "rose",
    standardVersion: "5.0.0",
  },
  {
    id: "V8",
    slug: "v5-authorization",
    title: "Authorization",
    description: "Access control design and enforcement for data, functions, resources, and privileges.",
    icon: "ShieldCheck",
    color: "orange",
    standardVersion: "5.0.0",
  },
  {
    id: "V9",
    slug: "v5-self-contained-tokens",
    title: "Self-contained Tokens",
    description: "Secure creation, validation, use, and lifecycle management of self-contained tokens.",
    icon: "TicketCheck",
    color: "amber",
    standardVersion: "5.0.0",
  },
  {
    id: "V10",
    slug: "v5-oauth-oidc",
    title: "OAuth and OIDC",
    description: "Secure OAuth 2.0 and OpenID Connect roles, flows, tokens, clients, and providers.",
    icon: "BadgeCheck",
    color: "yellow",
    standardVersion: "5.0.0",
  },
  {
    id: "V11",
    slug: "v5-cryptography",
    title: "Cryptography",
    description: "Approved cryptographic algorithms, key management, randomness, and secret protection.",
    icon: "Binary",
    color: "lime",
    standardVersion: "5.0.0",
  },
  {
    id: "V12",
    slug: "v5-secure-communication",
    title: "Secure Communication",
    description: "Transport security, trusted connections, certificate validation, and communication integrity.",
    icon: "LockKeyhole",
    color: "emerald",
    standardVersion: "5.0.0",
  },
{
    id: "V13",
    slug: "v5-configuration",
    title: "Configuration",
    description: "Secure configuration of application components, dependencies, environments, and external services.",
    icon: "Settings",
    color: "sky",
    standardVersion: "5.0.0",
  },
  {
    id: "V14",
    slug: "v5-data-protection",
    title: "Data Protection",
    description: "Data-at-rest and data-in-transit protection, privacy controls, and data lifecycle management.",
    icon: "Database",
    color: "red",
    standardVersion: "5.0.0",
  },
  {
    id: "V15",
    slug: "v5-secure-coding-architecture",
    title: "Secure Coding and Architecture",
    description: "Secure development practices, architecture principles, dependency management, and defensive coding.",
    icon: "Code2",
    color: "purple",
    standardVersion: "5.0.0",
  },
  {
    id: "V16",
    slug: "v5-logging-error-handling",
    title: "Security Logging and Error Handling",
    description: "Event logging, security monitoring, log protection, and safe error handling practices.",
    icon: "ScrollText",
    color: "gray",
    standardVersion: "5.0.0",
  },
  {
    id: "V17",
    slug: "v5-webrtc",
    title: "WebRTC",
    description: "Security requirements for WebRTC implementations including TURN servers, media, and signaling.",
    icon: "Video",
    color: "pink",
    standardVersion: "5.0.0",
  },
];

export function getCategoryBySlug(slug: string) {
  return categories.find((category) => category.slug === slug);
}

export function getCategoryById(id: string) {
  return categories.find((category) => category.id === id);
}
